title: Creating a timer
hero_image: images/banner.png
description: Create a timer using pause blocks, selection, and variables
version: 4
listed: false
copyedit: false
last_tested: "2023-09-22"
steps:
  - 
    title: Introduction
